enum COLOR {
  ALTO_GRAY = '#D5D5D5',
  ALTO_GRAY_DC = '#DCDCDC',
  BLACK = '#000000',
  CARIBBEAN_GREEN = '#6EDFAF',
  EERIE_BLACK = '#262626',
  GAINSBORO_GRAY = '#DDDDDD',
  GOLDEN_YELLOW = '#FFEE00',
  GRANITE_GRAY = '#5A5A5A',
  GRAY = '#8D8D8D',
  MINESHAFT_BLACK = '#383838',
  NOBEL_GRAY = '#b6b6b6',
  NERO = '#171717',
  QUICK_SILVER = '#9E9E9E',
  SNOW_WHITE = '#fafafa',
  WHITE = '#FFFFFF',
  ZAMBEZI_GRAY = '#5d5d5d',
}

export { COLOR };
